src/Entity/Design.php
<?php

namespace App\Entity;

use App\Repository\DesignRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DesignRepository::class)]
class Design
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column(length: 255)]
    private ?string $categorie = null;

    #[ORM\ManyToMany(targetEntity: Commande::class, inversedBy: 'designs')]
    private Collection $Commades;

    #[ORM\OneToMany(targetEntity: Avis::class, mappedBy: 'design')]
    private Collection $avis;

    #[ORM\ManyToMany(targetEntity: Competition::class, mappedBy: 'Designs')]
    private Collection $competitions;

    #[ORM\ManyToOne(inversedBy: 'designs')]
    #[ORM\JoinColumn(name: 'users_id', referencedColumnName: 'id')]
    private ?User $users = null;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    private ?string $picturePath = null;

    public function __construct()
    {
        $this->Commades = new ArrayCollection();
        $this->avis = new ArrayCollection();
        $this->competitions = new ArrayCollection();
        $this->picturePath = '';
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommades(): Collection
    {
        return $this->Commades;
    }

    public function addCommade(Commande $commade): static
    {
        if (!$this->Commades->contains($commade)) {
            $this->Commades->add($commade);
        }

        return $this;
    }

    public function removeCommade(Commande $commade): static
    {
        $this->Commades->removeElement($commade);

        return $this;
    }

    /**
     * @return Collection<int, Avis>
     */
    public function getAvis(): Collection
    {
        return $this->avis;
    }

    public function addAvi(Avis $avi): static
    {
        if (!$this->avis->contains($avi)) {
            $this->avis->add($avi);
            $avi->setDesign($this);
        }

        return $this;
    }

    public function removeAvi(Avis $avi): static
    {
        if ($this->avis->removeElement($avi)) {
            // set the owning side to null (unless already changed)
            if ($avi->getDesign() === $this) {
                $avi->setDesign(null);
            }
        }

        return $this;
    }

    /**
     * Get the average rating for this design
     */
    public function getAverageRating(): float
    {
        $totalRating = 0;
        $numAvis = count($this->avis);

        foreach ($this->avis as $avi) {
            $totalRating += $avi->getAvis();
        }

        if ($numAvis === 0) {
            return 0; // Return 0 if no reviews
        }

        return $totalRating / $numAvis;
    }

    /**
     * @return Collection<int, Competition>
     */
    public function getCompetitions(): Collection
    {
        return $this->competitions;
    }

    public function addCompetition(Competition $competition): static
    {
        if (!$this->competitions->contains($competition)) {
            $this->competitions->add($competition);
            $competition->addDesign($this);
        }

        return $this;
    }

    public function removeCompetition(Competition $competition): static
    {
        if ($this->competitions->removeElement($competition)) {
            $competition->removeDesign($this);
        }

        return $this;
    }

    public function getUsers(): ?User
    {
        return $this->users;
    }

    public function setUsers(?User $users): static
    {
        $this->users = $users;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getPicturePath(): ?string
    {
        return $this->picturePath;
    }

    public function setPicturePath(string $picturePath): self
    {
        $this->picturePath = $picturePath;

        return $this;
    }

    public function __toString(): string
    {
        return (string) $this->id;
    }
    
}

src/Form/DesignType.php
<?php

namespace App\Form;

use App\Entity\Design;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Length;

class DesignType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre', null, [
                'constraints' => [
                    new NotBlank(['message' => 'Title cannot be blank']), 
                    new Length([
                        'min' => 3,
                        'minMessage' => 'Title must be at least {{ limit }} characters long',
                    ]), 
                ],
            ])
            ->add('description', null, [
                'constraints' => [
                    new NotBlank(['message' => 'Description cannot be blank']), 
                ],
            ])
            ->add('prix', null, [
                'constraints' => [
                    new NotBlank(['message' => 'Price cannot be blank']), 
                ],
            ])
            ->add('categorie', ChoiceType::class, [
                'label' => 'Category',
                'choices' => [
                    'T-shirts' => 't_shirts',
                    'Hoodies' => 'hoodies',
                    'Pants' => 'pants',
                    'Dresses' => 'dresses',
                    'Jackets' => 'jackets',
                    'Sweatshirts' => 'sweatshirts',
                    'Skirts' => 'skirts',
                    'Sports Themes' => 'sports_Themes',
                    'Funniest and Troll' => 'Funny',
                    'Hats' => 'hat',
                ],
                'constraints' => [
                    new NotBlank(['message' => 'Category cannot be blank']), 
                ],
            ])
            ->add('picture', FileType::class, [
                'label' => 'Picture',
                'mapped' => false, 
                'required' => true, 
                'constraints' => [
                    new NotBlank(['message' => 'Please upload a picture']),
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Design::class,
        ]);
    }
}

src/Controller/DesignController.php
<?php

namespace App\Controller;
use Endroid\QrCode\ErrorCorrectionLevel\ErrorCorrectionLevelHigh;
use Endroid\QrCode\QrCode;
use App\Entity\Design;
use App\Entity\Avis;
use App\Entity\User;
use App\Form\DesignType;
use App\Repository\DesignRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Endroid\QrCode\Writer\PngWriter;
use Endroid\QrCode\Encoding\Encoding;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use Dompdf\Dompdf;
use Dompdf\Options;
use Endroid\QrCode\RoundBlockSizeMode\RoundBlockSizeModeInterface;
use Endroid\QrCode\Color\Color;
use Endroid\QrCode\ErrorCorrectionLevel\ErrorCorrectionLevelLow;
use Endroid\QrCode\Label\Label;
use Endroid\QrCode\Logo\Logo;
use Endroid\QrCode\RoundBlockSizeMode\RoundBlockSizeModeMargin;
use Endroid\QrCode\Writer\ValidationException;
use Endroid\QrCode\Label\Font\NotoSans;
use Symfony\Component\HttpFoundation\JsonResponse;
use Doctrine\Persistence\ManagerRegistry; 

#[Route('/design')]
class DesignController extends AbstractController
{
    //////////////////////////* Visitor Functions *//////////////////////////
  
   //* Design Details *//
   #[Route('/{design_id}', name: 'visitor_design_show', methods: ['GET'], requirements: ['design_id' => '\d+'])]
   public function showVisitor(int $design_id, DesignRepository $designRepository): Response
{
    $design = $designRepository->find($design_id);
    
    if (!$design) {
        throw $this->createNotFoundException('Design not found');
    }
    return $this->render('design/VisitorVue/Visitorshow.html.twig', [
        'design' => $design,
    ]);
}

   #[Route('/search', name: 'search_designs', methods: ['GET'])]
public function searchDesigns(Request $request, DesignRepository $designRepository): JsonResponse
{
    $query = $request->query->get('query');
    $designs = $designRepository->findBySearchQuery($query); // Implement this method in your repository

    // Serialize the designs to JSON format
    $data = [];
    foreach ($designs as $design) {
        $data[] = [
            'id' => $design->getId(),
            'title' => $design->getTitle(),
            'picture' => $design->getPicture(),
            'category' => $design->getCategory(),
        ];
    }

    return new JsonResponse($data);
}

    //* Store *//
    #[Route('/', name: 'Visitor_design_index', methods: ['GET'])]
    public function indexVisitor(Request $request, DesignRepository $designRepository): Response
{
    $currentPage = $request->query->getInt('page', 1);
    $totalDesigns = count($designRepository->findAll());
    $productsPerPage = 6;
    $totalPages = ceil($totalDesigns / $productsPerPage);

    $offset = ($currentPage - 1) * $productsPerPage;
    $designs = $designRepository->findBy([], null, $productsPerPage, $offset);

    return $this->render('design/VisitorVue/VisitorIndex.html.twig', [
        'designs' => $designs,
        'totalDesigns' => $totalDesigns,
        'totalPages' => $totalPages,
        'currentPage' => $currentPage,
        'productsPerPage' => $productsPerPage,
    ]);
}
/////////////////////////// QRCODE //////////////////
#[Route('/QrCode/{id}', name: 'app_QrCode')]
public function qrGenerator(ManagerRegistry $doctrine, $id, DesignRepository $designRepository)
{
    
    $design = $designRepository->find($id);
    
    if (!$design) {
        throw $this->createNotFoundException('Design not found');
    }

    $qrcode = QrCode::create($design->getTitre() .  " Et le prix est: " . $design->getPrix())
        ->setEncoding(new Encoding('UTF-8'))
        ->setSize(300)
        ->setMargin(10)
        ->setForegroundColor(new Color(0, 0, 0))
        ->setBackgroundColor(new Color(255, 255, 255));
    
    $writer = new PngWriter();
    $response = new Response($writer->write($qrcode)->getString(),
        Response::HTTP_OK,
        ['content-type' => 'image/png']
    );
    
    $disposition = $response->headers->makeDisposition(ResponseHeaderBag::DISPOSITION_ATTACHMENT, 'qrcode.png');
    $response->headers->set('Content-Disposition', $disposition);
    
    return $response;
}

    //////////////////////////* Client Functions *///////////////////////////
    #[Route('/client/{user_id}', name: 'app_design_index', methods: ['GET'])]
public function indexClient(Request $request,DesignRepository $designRepository, $user_id): Response
{
    $currentPage = $request->query->getInt('page', 1);
    $totalDesigns = count($designRepository->findAll());
    $productsPerPage = 6;
    $totalPages = ceil($totalDesigns / $productsPerPage);

    $offset = ($currentPage - 1) * $productsPerPage;
    $designs = $designRepository->findBy([], null, $productsPerPage, $offset);
    
    return $this->render('design/ClientVue/index.html.twig', [
        'designs' => $designs,
        'user_id' => $user_id,
        'totalDesigns' => $totalDesigns,
        'totalPages' => $totalPages,
        'currentPage' => $currentPage,
        'productsPerPage' => $productsPerPage,
    ]);
}


    
#[Route('/client/{users_id}/{design_id}', name: 'app_design_show', methods: ['GET'], requirements: ['id' => '\d+'], defaults: ['id' => null])]
public function showClient(int $users_id ,int $design_id, DesignRepository $designRepository): Response
{
    $design = $designRepository->find($design_id);
    
    if (!$design) {
        throw $this->createNotFoundException('Design not found');
    }
    return $this->render('design/ClientVue/show.html.twig', [
        'design' => $design,
        'users_id' => $users_id,
    ]);
}



    ////////////////////////////* Designer Functions *///////////////////////////

            //* Store *//
            #[Route('/designer/{users_id}', name: 'designer_design_index', methods: ['GET'])]
            public function indexDesigner(int $users_id, Request $request, DesignRepository $designRepository): Response
            {
                $currentPage = $request->query->getInt('page', 1);
                $productsPerPage = 6;
                $offset = ($currentPage - 1) * $productsPerPage;
            
                $designs = $designRepository->findBy([], null, $productsPerPage, $offset);
                $totalDesigns = count($designRepository->findAll());
            
                $totalPages = ceil($totalDesigns / $productsPerPage);
            
                return $this->render('design/DesignerVue/designerView.html.twig', [
                    'designs' => $designs,
                    'users_id' => $users_id,
                    'totalDesigns' => $totalDesigns,
                    'totalPages' => $totalPages,
                    'currentPage' => $currentPage,
                    'productsPerPage' => $productsPerPage,
                ]);
            }

            //* Own Store //*

            #[Route('/designer/myStore/{users_id}', name: 'app_design_by_designer', methods: ['GET'])]
            public function showStoreDesigner(int $users_id, DesignRepository $designRepository, Request $request): Response
                    {
                                $designs = $designRepository->findBy(['users' => $users_id]);

                        

                                 return $this->render('design/DesignerVue/DesignerProduct.html.twig', [
                                     'designs' => $designs,
                                     'users_id' => $users_id,
                                         ]);
                    }

                //* Add Design *//
                #[Route('/designer/{users_id}/new', name: 'app_design_new', methods: ['GET', 'POST'])]
                public function newDesign(int $users_id, Request $request, EntityManagerInterface $entityManager, ValidatorInterface $validator): Response
{
    $design = new Design();
    $user = $this->getDoctrine()->getRepository(User::class)->find($users_id);
    if (!$user) {
        throw $this->createNotFoundException('User not found');
    }
    $design->setUsers($user);
    
    $form = $this->createForm(DesignType::class, $design);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $pictureFile = $form['picture']->getData();
        if ($pictureFile) {
            $filename = md5(uniqid()) . '.' . $pictureFile->guessExtension();
            $pictureFile->move(
                $this->getParameter('pictures_directory'),
                $filename
            );
            $design->setPicture($filename);
        }

        $entityManager->persist($design);
        $entityManager->flush();

        return $this->redirectToRoute('app_design_by_designer', ['users_id' => $users_id], Response::HTTP_SEE_OTHER);
    }

    $errors = $validator->validate($design);

    return $this->renderForm('design/DesignerVue/new.html.twig', [
        'design' => $design,
        'form' => $form,
        'users_id' => $users_id,
        'errors' => $errors, 
    ]);
}
                
                
          //* Design Details in store*//
    #[Route('/designer/{users_id}/{design_id}', name: 'designer_design_show')]
    public function showDesignDesigner(int $users_id ,int $design_id, DesignRepository $designRepository): Response
    {
        $design = $designRepository->find($design_id);
    
        if (!$design) {
            throw $this->createNotFoundException('Design not found');
        }
    
        return $this->render('design/DesignerVue/DesignerShopDetails.html.twig', [
            'design' => $design,
            'users_id' => $users_id,

        ]);
    }

            //* store design show *//
    #[Route('/designer/mystore/{users_id}/{design_id}', name: 'designer_ownDesign_show')]

templates/design/VisitorVue/VisitorIndex.html.twig
{% extends 'VisitorBase.html.twig' %}

{% block title %}New Design - TFANNEN{% endblock %}

{% block banner_background %}
    data-background="{{ asset('assets/images/shop/banner2.jpg')}}"
{% endblock %}

{% block banner_title %}
       Welcome To Our Store
{% endblock %}

{% block banner_subtitle %}
   Shop
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        ::-webkit-slider-thumb {
            background: #fa4318;
        }

        ::-moz-range-thumb {
            background: #fa4318;
        }

        input[type="checkbox"] {
            appearance: none;
            -webkit-appearance: none;
            -moz-appearance: none;
            width: 20px;
            height: 20px;
            border: 1px solid #fa4318;
            border-radius: 3px;
            outline: none;
            cursor: pointer;
        }

        input[type="checkbox"]:checked {
            background-color: #fa4318;
        }
        /* Styling for the search bar */
        .search-input {
    width: calc(100% - 28px);
    padding: 8px;
    border: 1px solid #fa4318; /* Set border color */
    border-radius: 3px;
    outline: none;
}

.search-input:focus {
    border-color: #fa4318; /* Change border color on focus */
}
 .zoom-effect {
        transition: transform 0.3s ease;
    }

    .zoom-effect:hover {
        transform: scale(1.1); /* Adjust the scale value as needed */
    }
    /* Zoom effect for back-image */
    .zoom-effect-back {
        transition: transform 0.3s ease;
    }

    .zoom-effect-back:hover {
        transform: scale(1.1); /* Adjust the scale value as needed */
    }

    </style>
{% endblock %}

{% block body %}
<section class="product-area pt-130 pb-130">
    <div class="container">
        <div class="pb-20 bor-bottom shop-page-wrp d-flex justify-content-between align-items-center mb-65">
 <p class="fw-600">Showing {{ designs|length }} of {{ totalDesigns }} Designs</p>
            <div class="short">
                <select name="shortList" id="shortList" onchange="sortProducts(this.value)">
                    <option value="0">Short by :</option>
                    <option value="1">Highest Rate</option>
                    <option value="2">Newest</option>
                    <option value="3">oldest</option>
                    <option value="4">Highest Price </option>
                    <option value="5">Lowest Price </option>

                </select>
            </div>
        </div>
        <div class="row g-4">
            <div class="col-xl-3 col-lg-4">
                <div class="product__left-item sub-bg">
                    <div class="image mb-30">
                        <img src="{{ asset('assets/images/icons/filter.png')}}" alt="image">
                    </div>
                    <div class="product__content p-0">
                        <h4 class="mb-15"><a class="primary-hover">Price</a></h4>
                        <!-- Slider for Price -->
                        <input type="range" min="1" max="500" value="250" class="slider" id="priceSlider">
                        <p>Value: <span id="priceValue" style="color: #fa4318;">250</span> DT</p>
                    </div>
                    <div class="product__content p-0">
                        <h4 class="mb-15"><a class="primary-hover">Search</a></h4>
                        <!-- Search Bar -->
                                <input type="text" id="searchInput" class="search-input" placeholder="Search for designs..." onkeyup="searchDesigns()">
                    </div>
                    
                    <div class="image pt-40 mb-30 bor-top mt-40"></div>
                    <div class="product__content p-0">
                        <h4 class="mb-15"><a class="primary-hover">Category</a></h4>
                        <!-- Category Checkboxes -->
                        <label><input type="checkbox" value="t_shirts" class="category-filter"> T-shirts</label><br>
                        <label><input type="checkbox" value="hoodies" class="category-filter"> Hoodies</label><br>
                        <label><input type="checkbox" value="pants" class="category-filter"> Pants</label><br>
                        <label><input type="checkbox" value="dresses" class="category-filter"> Dresses</label><br>
                        <label><input type="checkbox" value="jackets" class="category-filter"> Jackets</label><br>
                        <label><input type="checkbox" value="sweatshirts" class="category-filter"> Sweatshirts</label><br>
                        <label><input type="checkbox" value="skirts" class="category-filter"> Skirts</label><br>
                        <label><input type="checkbox" value="sports_Themes" class="category-filter"> Sports Themes</label><br>
                        <label><input type="checkbox" value="Funny" class="category-filter"> Funniest and Troll</label><br>
                        <label><input type="checkbox" value="hat" class="category-filter"> Hats</label><br>
                    </div>
                </div>
            </div>

            <div class="col-xl-9 col-lg-8">
                <div class="row g-4" id="productList">
                   {% for design in designs %}
    <div class="col-xl-4 col-lg-6 col-md-6 product-item" data-price="{{ design.prix }}" data-category="{{ design.categorie }}" data-id="{{ design.id }}" data-average-rating="{{ design.averageRating }}">
        <div class="product__item bor">
            <a href="#0" class="wishlist"><i class="fa-regular fa-heart"></i></a>
            <a href="{{ path('visitor_design_show', {'design_id': design.id}) }}" class="product__image pt-20 d-block">
                <img class="font-image zoom-effect" src="{{ asset('uploads/' ~ design.picture) }}" alt="image">
                                <img class="back-image zoom-effect" src="{{ asset('uploads/' ~ design.picture) }}" alt="image">

            </a>
            <div class="product__content">
                <h4 class="mb-15"><a class="primary-hover" href="{{ path('visitor_design_show', {'design_id': design.id}) }}">{{ design.titre }}</a></h4>
                <span class="primary-color">{{ design.prix }} DT</span>
                <div class="star mt-20">
                    {% set averageRating = design.getAverageRating() %}
                    {% for i in 1..5 %}
                        {% if i <= averageRating %}
                            <i class="fa-solid fa-star"></i>
                        {% else %}
                            <i class="far fa-star"></i>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <a class="product__cart d-block bor-top" href="{{ path('app_login') }}"><i class="fa-regular fa-cart-shopping primary-color me-1"></i> <span>Add to cart</span></a>
        </div>
    </div>
{% else %}
                    <div class="col-12">
                        <p>Sorry! No Product found, Visit us later</p>
                    </div>
                    {% endfor %}
                </div>
                <div class="pagi-wrp mt-65">
            {% for page in 1..totalPages %}
                <a href="{{ path('Visitor_design_index', {'page': page}) }}" class="pagi-btn {% if page == currentPage %}active{% endif %}">{{ page }}</a>
            {% endfor %}
        </div>
            </div>
        </div>
    </div>
</section>

<script>
    var slider = document.getElementById("priceSlider");
    var output = document.getElementById("priceValue");
    output.innerHTML = slider.value;

    slider.oninput = function() {
        output.innerHTML = this.value;
        filterProducts(parseInt(this.value));
    }

    function filterProducts(price) {
        var products = document.getElementsByClassName("product-item");
        var selectedCategories = getSelectedCategories();
        for (var i = 0; i < products.length; i++) {
            var productPrice = parseInt(products[i].getAttribute("data-price"));
            var productCategory = products[i].getAttribute("data-category");
            if (productPrice > price || (selectedCategories.length > 0 && !selectedCategories.includes(productCategory))) {
                products[i].style.display = "none";
            } else {
                products[i].style.display = "block";
            }
        }
    }

    function getSelectedCategories() {
        var checkboxes = document.getElementsByClassName("category-filter");
        var selectedCategories = [];
        for (var i = 0; i < checkboxes.length; i++) {
            if (checkboxes[i].checked) {
                selectedCategories.push(checkboxes[i].value);
            }
        }
        return selectedCategories;
    }

    var categoryCheckboxes = document.getElementsByClassName("category-filter");
    for (var i = 0; i < categoryCheckboxes.length; i++) {
        categoryCheckboxes[i].addEventListener("change", function() {
            filterProducts(parseInt(slider.value));
        });
    }

    function searchDesigns() {
        var input, filter, productList, productItem, title, i, txtValue;
        input = document.getElementById('searchInput');
        filter = input.value.toUpperCase();
        productList = document.getElementById("productList");
        productItem = productList.getElementsByClassName('product-item');

        for (i = 0; i < productItem.length; i++) {
            title = productItem[i].getElementsByTagName("h4")[0];
            txtValue = title.textContent || title.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                productItem[i].style.display = "";
            } else {
                productItem[i].style.display = "none";
            }
        }
    }
function sortProducts(sortBy) {
    var productList = document.getElementById("productList");
    var productItems = productList.querySelectorAll('.product-item');

    // Convert NodeList to array for easier sorting
    var productArray = Array.from(productItems);

    switch (sortBy) {
        case '1':
            // Highest Rate - Sort by highest average rating
            productArray.sort((a, b) => {
                let averageRatingA = parseFloat(a.dataset.averageRating);
                let averageRatingB = parseFloat(b.dataset.averageRating);
                return averageRatingB - averageRatingA;
            });
            break;
        case '2':
            // Newest (Highest ID to Lowest ID)
            productArray.sort((a, b) => {
                return parseInt(b.getAttribute('data-id')) - parseInt(a.getAttribute('data-id'));
            });
            break;
        case '3':
            // Oldest (Lowest ID to Highest ID)
            productArray.sort((a, b) => {
                return parseInt(a.getAttribute('data-id')) - parseInt(b.getAttribute('data-id'));
            });
            break;
        case '4':
            // Highest Price
            productArray.sort((a, b) => {
                return parseFloat(b.dataset.price) - parseFloat(a.dataset.price);
            });
            break;
        case '5':
            // Lowest Price
            productArray.sort((a, b) => {
                return parseFloat(a.dataset.price) - parseFloat(b.dataset.price);
            });
            break;
        default:
            // Default sorting (show as it is in HTML)
            break;
    }

    // Re-append sorted product items to productList
    productList.innerHTML = '';
    productArray.forEach(item => {
        productList.appendChild(item);
    });
}


</script>
{% endblock %}