src/Entity/Promotion.php
<?php

namespace App\Entity;

use App\Repository\PromotionRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert; 
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
#[ORM\Entity(repositoryClass: PromotionRepository::class)]
class Promotion
{
    
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'le nom  est obligatoire!')]
    #[Assert\Length(max:30, maxMessage:'Le nom ne peut pas dépasser {{ limit }} caractères.')]
    #[Assert\Length(min:5, minMessage:'Le nom doit au minimum avoir {{ limit }} caractères.')]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'description  est obligatoire!')]
    #[Assert\Length(max:255, maxMessage:'La description ne peut pas dépasser {{ limit }} caractères.')]
    #[Assert\Length(min:5, minMessage:'La description doit au minimum avoir {{ limit }} caractères.')]
    private ?string $description = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: 'taux_reduction est obligatoire!')]
    #[Assert\Positive(message:'La récompense doit etre positive.')]
    private ?float $taux_reduction = null;

    #[ORM\Column(length: 255)]
    #[Assert\Regex( pattern:"/^#/",message:"Code promo should start with '#'")]
    private ?string $code_promo = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank(message: 'La date de début est obligatoire!')]
    #[Assert\GreaterThanOrEqual("today",message: 'La date de début doit être supérieure ou égale à la date d\'aujourd\'hui!')]
    #[Assert\LessThan(propertyPath: 'dateFin', message:'La date de début doit être inférieure à la date de fin!')]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank(message: 'La date de fin est obligatoire!')]
    #[Assert\GreaterThan(propertyPath: 'dateDebut',message: 'La date de fin doit être supérieure à la date de début!')]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'type_promo  est obligatoire!')]
    private ?string $type_promo = null;
    #[ORM\OneToMany(targetEntity: Commande::class, mappedBy: 'promotion')]
    private Collection $Commandes;

    public function __construct()
    {
        $this->Commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getTauxReduction(): ?float
    {
        return $this->taux_reduction;
    }

    public function setTauxReduction(float $taux_reduction): static
    {
        $this->taux_reduction = $taux_reduction;

        return $this;
    }

    public function getCodePromo(): ?string
    {
        return $this->code_promo;
    }

    public function setCodePromo(string $code_promo): static
    {
        $this->code_promo = $code_promo;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getTypePromo(): ?string
    {
        return $this->type_promo;
    }

    public function setTypePromo(string $type_promo): static
    {
        $this->type_promo = $type_promo;

        return $this;
    }
}

src/Form/PromotionType.php
<?php
namespace App\Form;

use App\Entity\Promotion;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;


class PromotionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('taux_reduction')
         ->add('type_promo', ChoiceType::class, [
    'choices' => [
        'Promo générale' => 'promo_generale',
        'Code promo' => 'code_promo', 
        /*'Promotion mbr d\'utilisateurs' => 'min_utilisateur',
        'Promotionmin montant d\'achat ' => 'min_montant',*/
    ],
    'label' => 'Type de promotion',
    'multiple' => false,
    'expanded' => true,
    'attr' => ['class' => 'promo-type'],
    'choice_attr' => function($choice, $key, $value) {
        return ['style' => 'display: block; margin-bottom: 5px;margin-right: 10px;margin-left: 10px;'];
    }
])
           
            
            ->add('code_promo')
          //  ->add('min_utilisateur')
           // ->add('min_montant')
            ->add('date_debut')
            ->add('date_fin');

      
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Promotion::class,
        ]);
    }
}

src/Controller/PromotionController.php
<?php

namespace App\Controller;

use App\Entity\Promotion;
use App\Form\PromotionType;
use App\Service\TwilioService;
use App\Service\mail;

use App\Repository\PromotionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/promotion')]
class PromotionController extends AbstractController
{
    #[Route('/', name: 'app_promotion_index', methods: ['GET'])]
    public function index(PromotionRepository $promotionRepository): Response
    {
        return $this->render('promotion/index.html.twig', [
            'promotions' => $promotionRepository->findAll(),
        ]);
    }
    //admin
    #[Route('/dash', name: 'app_promotion_dash', methods: ['GET'])]
    public function index1(PromotionRepository $promotionRepository): Response
    {
        return $this->render('promotion/index1.html.twig', [
            'promotions' => $promotionRepository->findAll(),
        ]);
    }

    #[Route('/dash/add', name: 'app_promotion_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager,mail $mailMessage): Response
    {
        
        $promotion = new Promotion();
        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
          /*  $number = '+21692503961'; // Example phone number
            $name = 'Tfannen platforme'; // Example name
            $text = 'promo flash ! new promotion is added to our platform '; // Example text
            $twilioService->sendSms($number, $name, $text);*/
            $to = 'ayedhamza970@gmail.com'; // Define the recipient email address
            $content = 'promo flash ! new promotion is added to our platform'; // Define the email content
            $subject = 'tfannen platform';
            $mailMessage->sendEmail($to, $content, $subject);

            
            $entityManager->persist($promotion);
            $entityManager->flush();

            return $this->redirectToRoute('app_promotion_dash', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderform('promotion/new.html.twig', [
            'promotion' => $promotion,
            'form' => $form,
        ]);
    }

    #[Route('/dash/show/{id}', name: 'app_promotion_show', methods: ['GET'])]
    public function show(Promotion $promotion): Response
    {
        return $this->renderform('promotion/show.html.twig', [
            'promotion' => $promotion,
        ]);
    }

    #[Route('/dash/edit/{id}', name: 'app_promotion_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Promotion $promotion, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_promotion_dash', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderform('promotion/edit.html.twig', [
            'promotion' => $promotion,
            'form' => $form,
        ]);
    }

    #[Route("/dash/delete/{id}", name:"app_promotion_delete")]
    
public function delete($id, EntityManagerInterface $entityManager): Response
{
    $promotion = $entityManager->getRepository(Promotion::class)->find($id);

    if (!$promotion) {
        $this->addFlash('error', 'promotion not found.');
    } else {
        $entityManager->remove($promotion);
        $entityManager->flush();

        $this->addFlash('success', 'User deleted successfully.');
    }

    return $this->redirectToRoute('app_promotion_dash');
}
   




// Controller action to validate promo code and calculate discounted price
public function checkPromoCode(Request $request): JsonResponse
{
    $promoCode = $request->get('promoCode');
    $designId = $request->get('designId');
    $designPrice = $request->get('designPrice');

    // Perform validation and get the discounted price from your database or logic
    $discountedPrice = $this->getDiscountedPrice($promoCode, $designId, $designPrice);

    // Send the discounted price back to the JavaScript function in the template
    return new JsonResponse(['discountedPrice' => $discountedPrice]);
}

}

templates/promotion/_delete_form.html.twig
<form method="post" action="{{ path('app_promotion_delete', {'id': promotion.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ promotion.id) }}">
    <button class="btn">Delete</button>
</form>

templates/promotion/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/promotion/edit.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}New Promotion - TFANNEN{% endblock %}

{% block banner_background %}
    data-background="{{ asset('assets/images/shop/banner.jpg')}}"
{% endblock %}

{% block banner_title %}
    Create a New Promotion
{% endblock %}

{% block banner_subtitle %}
    Fill in the details to create a new Promotion
{% endblock %}




{% block body %}
    <!-- Your page content goes here -->
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <section class="contact pt-130 pb-130">
                    <div class="container">
                        <div class="row g-4">
                            
                            <div class="col-lg-6">
                                <div class="form-area">
                                     
                                    <div class="col-12">
                                          <h1>Edit Promotion</h1>

    {{ include('promotion/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_promotion_dash') }}">back to list</a>
    <br>
    {{ include('promotion/_delete_form.html.twig') }}
   

</div>

    

  

 


                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
{% endblock %}

templates/promotion/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Promotion - TFANNEN{% endblock %}

{% block banner_background %}
    data-background="{{ asset('assets/images/promo.jpg')}}"
{% endblock %}

{% block banner_title %}
 <!-- Home content -->
		<div id="home-content">
			<div id="content-inner" class="text-center">
				<!-- Arrow down-->
				<a href="#promotions" title="About" class="smooth-scroll" id="arrow-down">
					<i class="fas fa-angle-down"></i>
				</a>
			</div>
		</div>
{% endblock %}






{% block body %}
  
                                        

    
<section id="promotion" >
    <table class="table">
        <thead>
            <tr>
               
                <th>name</th>
                <th>Description</th>
                <th>Taux_reduction</th>
                <th>Type_promo</th>
                <th>Code_promo</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
            </tr>
        </thead>
        <tbody>
        {% for promotion in promotions %}
            <tr>
                <td>{{ promotion.name }}</td>
                <td>{{ promotion.description }}</td>
                <td>{{ promotion.tauxReduction }}</td>
                <td>{{ promotion.typePromo }}</td>
                <td>{{ promotion.codePromo }}</td>
                <td>{{ promotion.dateDebut ? promotion.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ promotion.dateFin ? promotion.dateFin|date('Y-m-d') : '' }}</td>
              
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    
                                    </div>
                                   
    <!-- Your page content goes here -->
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <section class="contact pt-130 pb-130">
                    <div class="container">
                        <div class="row g-4">
                            
                            <div class="col-lg-6">
                                <div class="form-area">
                                     
                                 
                                   
                                  
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    </section>
{% endblock %}

templates/promotion/index1.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}New Promotion - TFANNEN{% endblock %}

{% block banner_background %}
    data-background="{{ asset('assets/images/shop/banner2.jpg')}}"
{% endblock %}

{% block banner_title %}
    Create a New Promotion
{% endblock %}

{% block banner_subtitle %}
    Fill in the details to create a new Promotion
{% endblock %}




{% block body %}
   <div class="col-12">
                                        

     <h1>Promotion index</h1>

    <table class="table">
        <thead>
            <tr>
                
                <th>name</th>
                <th>Description</th>
                <th>Taux_reduction</th>
                <th>Type_promo</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for promotion in promotions %}
            <tr>
                
                <td>{{ promotion.name }}</td>
                <td>{{ promotion.description }}</td>
                <td>{{ promotion.tauxReduction }}</td>
                 <td>{{ promotion.typePromo }}</td>
                <td>{{ promotion.dateDebut ? promotion.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ promotion.dateFin ? promotion.dateFin|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_promotion_show', {'id': promotion.id}) }}">show</a>
                    &nbsp;&nbsp;
                    <a href="{{ path('app_promotion_edit', {'id': promotion.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    
                                    </div>
                                   
    <!-- Your page content goes here -->
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <section class="contact pt-130 pb-130">
                    <div class="container">
                        <div class="row g-4">
                            
                            <div class="col-lg-6">
                                <div class="form-area">
                                     
                                 
                                   
                                    <div class="col-12">
                                    <a href="{{ path('app_promotion_new') }}"><button class="mt-40 btn-one" type="submit"><span>Create new Promotion    </span></button></a>
                                        
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
{% endblock %}

templates/promotion/new.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}New Promotion - TFANNEN{% endblock %}

{% block banner_background %}
    data-background="{{ asset('assets/images/shop/banner2.jpg')}}"
{% endblock %}

{% block banner_title %}
    Create a Promotion
{% endblock %}

{% block banner_subtitle %}
    Fill in the details to create a new Promotion
{% endblock %}

{% block body %}
    <!-- Your page content goes here -->
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <section class="contact pt-130 pb-130">
                    <div class="container">
                        <div class="row g-4">
                            
                            <div class="col-lg-6">
                                <div class="form-area">
                                    {{ form_start(form, {'attr': {'novalidate': 'novalidate'}} ) }}
                                     <div class="col-12">
                                        {{ form_label(form.name, 'name', {'label_attr': {'class': 'form-label'}}) }}
                                        {{ form_widget(form.name, {'attr': {'class': 'form-control'}}) }}
                                        {{ form_errors(form.name, {'attr': {'class': 'text_danger'}}) }}
                                    </div>
                                   <div class="col-12">
                                        {{ form_label(form.description, 'description', {'label_attr': {'class': 'form-label'}}) }}
                                        {{ form_widget(form.description, {'attr': {'class': 'form-control'}}) }}
                                        {{ form_errors(form.description, {'attr': {'class': 'text_danger'}}) }}
                                    </div>
                                    <div class="col-12">
                                        {{ form_label(form.taux_reduction, 'taux_reduction', {'label_attr': {'class': 'form-label'}}) }}
                                        {{ form_widget(form.taux_reduction, {'attr': {'class': 'form-control'}}) }}
                                        {{ form_errors(form.taux_reduction, {'attr': {'class': 'text_danger'}}) }}
                                    </div>
                                    <div class="col-12">
                                        {{ form_label(form.type_promo, 'type_promo', {'label_attr': {'class': 'form-label'}}) }}
                                        {{ form_widget(form.type_promo, {'attr': {'class': 'form-control'}}) }}
                                         {{ form_errors(form.type_promo, {'attr': {'class': 'text_danger'}}) }}
                                        
                                    </div>
                                    <div class="col-12" id="code_promo_field" style="display: none;">
                                       {{ form_label(form.code_promo, 'code_promo', {'label_attr': {'class': 'form-label'}}) }}
                                       {{ form_widget(form.code_promo, {'attr': {'class': 'form-control'}}) }}
                                       {{ form_errors(form.code_promo, {'attr': {'class': 'text_danger'}}) }}
                                    </div>
                                    

                                    <div class="col-12">
                                        {{ form_label(form.date_debut, 'date_debut', {'label_attr': {'class': 'form-label'}}) }}
                                        {{ form_widget(form.date_debut, {'attr': {'class': 'form-control'}}) }}
                                         {{ form_errors(form.date_debut, {'attr': {'class': 'text_danger'}}) }}
                                    </div>
                                    <div class="col-12">
                                        {{ form_label(form.date_fin, 'date_fin', {'label_attr': {'class': 'form-label'}}) }}
                                        {{ form_widget(form.date_fin, {'attr': {'class': 'form-control'}}) }}
                                         {{ form_errors(form.date_fin, {'attr': {'class': 'text_danger'}}) }}
                                    </div>
                               <div class="col-12">
    
</div>
                                    <div class="col-12">
                                    <br>
                                        <button class="mt-40 btn-one" type="submit"><span>ADD Promotion</span></button>
                                    </div>
                                    {{ form_end(form) }}
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
 <script>
    document.addEventListener('DOMContentLoaded', function() {
        var typePromoRadios = document.querySelectorAll('input[name="promotion[type_promo]"]');
        var codePromoField = document.getElementById('code_promo_field');
       
        

        typePromoRadios.forEach(function(radio) {
            radio.addEventListener('change', function() {
                if (this.value === 'code_promo') {
                    codePromoField.style.display = 'block';
                      minMontantField.style.display = 'none';
                    minMontantField.value = '-';
                     minUtiisateurField.style.display = 'none';
                    minUtiisateurField.value = '-';
                  
                   
                } 
                else {
                    codePromoField.style.display = 'none';
                    codePromoField.value = '-';
                
                 
                   
                }
            });
        });
    });
</script>


            
{% endblock %}

templates/promotion/show.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}Promotion{% endblock %}

{% block body %}
    <h1>Promotion</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ promotion.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ promotion.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ promotion.description }}</td>
            </tr>
            <tr>
                <th>Taux_reduction</th>
                <td>{{ promotion.tauxReduction }}</td>
            </tr>
            <tr>
                <th>Type_promo</th>
                <td>{{ promotion.typePromo }}</td>
            </tr>
            <tr>
                <th>Code_promo</th>
                <td>{{ promotion.codePromo }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ promotion.dateDebut ? promotion.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ promotion.dateFin ? promotion.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_promotion_dash') }}">back to list</a>
    &nbsp;&nbsp;

    <a href="{{ path('app_promotion_edit', {'id': promotion.id}) }}">edit</a>

    {{ include('promotion/_delete_form.html.twig') }}
{% endblock %}